export const Routes = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  ACCOUNT_SETTINGS: '/account/settings',
  PROJECTS: '/projects',
  DATA_SOURCES: '/data-sources',
  CLUSTERS: '/clusters',
  ORG_SETTINGS: '/organization/settings',
  PROJECT_DETAILS: '/projects/:projectId',
  PROJECT_WORKSPACES: '/projects/:projectId/workspaces',
  PROJECT_DATASETS: '/project/:projectId/datasets',
  PROJECT_DATASET_DETAILS: '/projects/:projectId/datasets/:datasetId',
  PROJECT_SETTINGS: '/projects/:projectId/settings',
  PROJECT_EXPERIMENTS: '/projects/:projectId/experiments',
  PROJECT_NOTEBOOKS: '/projects/:projectId/notebooks',
};
