---
title: Lilac
icons:
    - name: logos
      url: https://unpkg.com/@iconify-json/logos@1/icons.json
config:
  theme: 'default'
  
---
architecture-beta
    group lilac[Lilac]
    group cloud(cloud)[Lilac Cloud] in lilac
    group oss(logos:github-icon)[Open Source] in lilac

    service db(logos:postgresql)[PostgreSQL] in oss
    service k8s(logos:kubernetes)[Kubernetes] in oss
    service api(internet)[API] in oss
    service auth(server)[SSO] in oss

    service eks(logos:aws-eks)[EKS] in cloud

    db:R <-- L:k8s
    api:L --> R:auth
    api:B --> T:k8s
    api:B --> T:db
    