export enum Routes {
  LOGIN = '/login',
  LOGOUT = '/logout',
  SIGNUP = '/signup',
  ACCOUNT_SETTINGS = '/account/settings',
  ORGANIZATIONS = '/organizations',
  ORGANIZATION_SETTINGS = '/organizations/:organizationId/settings',
  ORGANIZATION_PROJECTS = '/organizations/:organizationId/projects',
  PROJECT_DETAILS = '/projects/:projectId',
  PROJECT_PIPELINES = '/projects/:projectId/pipelines',
  PROJECT_PIPELINE_DETAILS = '/projects/:projectId/pipelines/:pipelineId',
  PROJECT_DATASETS = '/projects/:projectId/datasets',
  PROJECT_DATASET_DETAILS = '/projects/:projectId/datasets/:datasetId',
  PROJECT_SETTINGS = '/projects/:projectId/settings',
}
